# Generated by Django 5.1.3 on 2024-11-22 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_summary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_logs', to='pdf_summary.pdfsummary')),
            ],
        ),
    ]
