# Generated by Django 5.1.3 on 2024-11-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_summary', '0002_chatlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfsummary',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='pdfsummary',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
