# Generated by Django 5.1.3 on 2025-02-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_summary', '0003_pdfsummary_pdf_file_alter_pdfsummary_pdf_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfsummary',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='pdfsummary',
            name='pdf_file_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
